services:
  mysql:
    container_name: mysql-bsn
    image: mysql
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MSDATA: /var/lib/mysql/data
      MYSQL_DB: book_social_network
    volumes:
      - mysql:/data/mysql
    ports:
      - 3308:3308
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge
volumes:
  mysql:
    driver: local